all_products = [
    "BAGUETTE", "PAIN AU CHOCOLAT", "PAIN TRADITIONAL", "BAGUETTE CROISSANT", "BANETTE", 
    "BANETTINE", "SPECIAL BREAD", "COUPE SAND JB EMMENTAL", "KOUIGN AMANN", "BOULE 200G", 
    "BOULE 400G", "GAL FRANGIPANE 6P", "CAMPAGNE", "MOISSON", "CAFE OU EAU", "BRIOCHE", 
    "CEREAL BAGUETTE", "SEIGLE COMPLET", "DIVERS PATISSERIE", "GAL FRANGIPANE 4P", "COOKIE", 
    "FICELLE", "PAIN AUX RAISINS", "GAL POMME 6P", "GAL POMME 4P", "FINANCIER X5", "VIK BREAD", 
    "DIVERS VIENNOISERIE", "GACHE", "SANDWICH COMPLET", "PAIN BANETTE", "GRAND FAR BRETON", 
    "QUIM BREAD", "SPECIAL BREAD KG", "GD KOUIGN AMANN", "BOULE POLKA", "DEMI BAGUETTE", 
    "CHAUSSON AUX POMMES", "BAGUETTE GRAINE", "DIVERS CONFISERIE", "SUCETTE", 
    "DIVERS BOULANGERIE", "BOISSON 33CL", "PATES", "FORMULE SANDWICH", "DIVERS SANDWICHS", 
    "CROISSANT AMANDES", "PAIN CHOCO AMANDES", "SACHET VIENNOISERIE", "NANTAIS CHOCOLAT", 
    "PAIN S/SEL", "FONDANT CHOCOLAT", "GAL POIRE CHOCO 6P", "GAL POIRE CHOCO 4P", "GALETTE 8 PERS", 
    "SAND JB", "SACHET DE CROUTON", "GRANDE SUCETTE", "DEMI PAIN", "TARTELETTE FLAN", "PARIS BREST", 
    "SAVARIN", "FLAN ABRICOT", "BAGUETTE APERO", "MILLES FEUILLES", "CHOU CHANTILLY", "ECLAIR", 
    "ROYAL 4P", "TARTE FRUITS 6P", "TARTE FRUITS 4P", "NOIX JAPONAISE", "THE", "BRIOCHETTE", 
    "ROYAL 6P", "ECLAIR FRAISE PISTACHE", "GD FAR BRETON", "TRIANGLES", "TROPEZIENNE", 
    "TROPEZIENNE FRAMBOISE", "ROYAL", "TARTE FRAISE 6P", "TARTELETTE FRAISE", "TARTE FRAISE 4PER", 
    "FRAISIER", "NID DE POULE", "TARTELETTE CHOC", "PAIN DE MIE", "CRUMBLE", "FINANCIER", 
    "DIVERS BOISSONS", "CAKE", "VIENNOISE", "TRAITEUR", "PAIN GRAINES", "PLATPREPARE6,50", 
    "PLATPREPARE5,50", "PLATPREPARE7,00", "FORMULE PLAT PREPARE", "ST HONORE", "BROWNIES", 
    "RELIGIEUSE", "PLATPREPARE6,00", "DELICETROPICAL", "CRUMBLECARAMEL OU PISTAE", "PT NANTAIS", 
    "GD NANTAIS", "DOUCEUR D HIVER", "TROIS CHOCOLAT", "ARTICLE 295", "TARTE FINE", "ENTREMETS", 
    "BRIOCHE DE NOEL", "FRAMBOISIER", "BUCHE 4PERS", "BUCHE 6PERS", "GD PLATEAU SALE", "BUCHE 8PERS", 
    "PT PLATEAU SALE", "REDUCTION SUCREES 12", "PAIN NOIR", "REDUCTION SUCREES 24", "BOTTEREAU", 
    "MERINGUE", "PALMIER", "PAILLE", "PLAT 6.50E", "PLAT 7.60E", "PLAT 7.00", "PLAT", "PLAT 8.30E", 
    "FORMULE PATE", "GUERANDAIS", "PALET BRETON", "CARAMEL NOIX", "MACARON 12", "MACARON", 
    "ARMORICAIN", "PLAQUE TARTE 25P", "SABLE F  P", "PAIN SUISSE", "PEPITO", "TULIPE", 
    "TARTELETTE COCKTAIL", "SACHET DE VIENNOISERIE"
]

groups = [
    "Breads", "Viennoiseries", "Pastries", "Cakes", "Tarts", "Sandwiches", 
    "Specialty Breads", "Confectionery", "Beverages", "Prepared Meals", 
    "Seasonal/Holiday Items", "Snacks", "Cookies and Biscuits", 
    "Traditional French Desserts", "Traiteur", "Breakfast Items", 
    "Party Platters", "Dietary Specific", "Miscellaneous Baked Goods", 
    "Ingredients and Supplies"
]